// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooTrack.Data;

#nullable disable

namespace ZooTrackBackend.Migrations
{
    [DbContext(typeof(ZootrackDbContext))]
    [Migration("20251017070320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ZooTrack.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlertId");

                    b.HasIndex("DetectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ZooTrack.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("ConfidenceLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("DetectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AnimalId");

                    b.HasIndex("DetectionId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ZooTrack.Models.Detection", b =>
                {
                    b.Property<int>("DetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BoundingBoxHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("REAL");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedObject")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetectionId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventId");

                    b.HasIndex("MediaId");

                    b.ToTable("Detections");

                    b.HasData(
                        new
                        {
                            DetectionId = 1,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 92f,
                            DetectedAt = new DateTime(2025, 10, 15, 15, 3, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "tiger",
                            DeviceId = 1,
                            EventId = 1,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 1
                        },
                        new
                        {
                            DetectionId = 2,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 95f,
                            DetectedAt = new DateTime(2025, 10, 16, 15, 2, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "elephant",
                            DeviceId = 2,
                            EventId = 2,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 3
                        },
                        new
                        {
                            DetectionId = 3,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 87f,
                            DetectedAt = new DateTime(2025, 10, 16, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "giraffe",
                            DeviceId = 2,
                            EventId = 2,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 4
                        },
                        new
                        {
                            DetectionId = 4,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 91f,
                            DetectedAt = new DateTime(2025, 10, 17, 11, 2, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "lion",
                            DeviceId = 4,
                            EventId = 3,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 5
                        },
                        new
                        {
                            DetectionId = 5,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 89f,
                            DetectedAt = new DateTime(2025, 10, 17, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "wolf",
                            DeviceId = 4,
                            EventId = 3,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 5
                        },
                        new
                        {
                            DetectionId = 6,
                            BoundingBoxHeight = 0f,
                            BoundingBoxWidth = 0f,
                            BoundingBoxX = 0f,
                            BoundingBoxY = 0f,
                            Confidence = 94f,
                            DetectedAt = new DateTime(2025, 10, 17, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            DetectedObject = "bear",
                            DeviceId = 1,
                            EventId = 5,
                            FrameNumber = 0,
                            IsTarget = false,
                            MediaId = 1
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.DetectionValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFalseNegative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTruePositive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectionId");

                    b.ToTable("DetectionValidations");
                });

            modelBuilder.Entity("ZooTrack.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            LastActive = new DateTime(2025, 10, 17, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            Location = "North Zone",
                            Status = "Online"
                        },
                        new
                        {
                            DeviceId = 2,
                            LastActive = new DateTime(2025, 10, 17, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            Location = "South Zone",
                            Status = "Online"
                        },
                        new
                        {
                            DeviceId = 3,
                            LastActive = new DateTime(2025, 10, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "East Zone",
                            Status = "Offline"
                        },
                        new
                        {
                            DeviceId = 4,
                            LastActive = new DateTime(2025, 10, 17, 14, 58, 0, 0, DateTimeKind.Unspecified),
                            Location = "West Zone",
                            Status = "Online"
                        },
                        new
                        {
                            DeviceId = 5,
                            LastActive = new DateTime(2025, 10, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Central Zone",
                            Status = "Maintenance"
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EndTime = new DateTime(2025, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            EventId = 2,
                            EndTime = new DateTime(2025, 10, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            EventId = 3,
                            EndTime = new DateTime(2025, 10, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            EventId = 4,
                            EndTime = new DateTime(2025, 10, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            EventId = 5,
                            EndTime = new DateTime(2025, 10, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DetectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("DetectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            ActionType = "Login",
                            Level = "Info",
                            Message = "Admin logged into system",
                            Timestamp = new DateTime(2025, 10, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            LogId = 2,
                            ActionType = "Detection_Review",
                            DetectionId = 1,
                            Level = "Info",
                            Message = "Validated tiger detection",
                            Timestamp = new DateTime(2025, 10, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            LogId = 3,
                            ActionType = "Login",
                            Level = "Info",
                            Message = "Zoo Manager logged into system",
                            Timestamp = new DateTime(2025, 10, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MediaId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            DeviceId = 1,
                            FilePath = "Media/Videos/video1.mp4",
                            Timestamp = new DateTime(2025, 10, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Video"
                        },
                        new
                        {
                            MediaId = 2,
                            DeviceId = 1,
                            FilePath = "Media/Images/image1.jpg",
                            Timestamp = new DateTime(2025, 10, 15, 15, 3, 0, 0, DateTimeKind.Unspecified),
                            Type = "Image"
                        },
                        new
                        {
                            MediaId = 3,
                            DeviceId = 2,
                            FilePath = "Media/Videos/video2.mp4",
                            Timestamp = new DateTime(2025, 10, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Video"
                        },
                        new
                        {
                            MediaId = 4,
                            DeviceId = 2,
                            FilePath = "Media/Images/image2.jpg",
                            Timestamp = new DateTime(2025, 10, 16, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            Type = "Image"
                        },
                        new
                        {
                            MediaId = 5,
                            DeviceId = 4,
                            FilePath = "Media/Videos/video3.mp4",
                            Timestamp = new DateTime(2025, 10, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Video"
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.TrackingRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedObject")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrackingRoutes");
                });

            modelBuilder.Entity("ZooTrack.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Admin",
                            Name = "Admin",
                            PasswordHash = "ERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAx",
                            PasswordSalt = "AQIDBAUEDF+CAQIDBAUGCQ0ODw==",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "manager@zootrack.com",
                            Name = "Zoo Manager",
                            PasswordHash = "UVJTVFVWVxhZWltcXV5fYGFiY2RlZmdoaWprbG1ub3A=",
                            PasswordSalt = "ITIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1A=",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "observer@zootrack.com",
                            Name = "Wildlife Observer",
                            PasswordHash = "kZKTlJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7A=",
                            PasswordSalt = "cXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5A=",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.UserSettings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DetectionThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("HighlightSavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationPreference")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAnimalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DetectionThreshold = 0.8f,
                            HighlightSavePath = "Media/HighlightFrames/Admin",
                            NotificationPreference = "Email",
                            TargetAnimalsJson = "[\"person\",\"dog\",\"cow\",\"wolf\",\"tiger\",\"lion\",\"elephant\",\"giraffe\"]"
                        },
                        new
                        {
                            UserId = 2,
                            DetectionThreshold = 0.75f,
                            HighlightSavePath = "Media/HighlightFrames/Manager",
                            NotificationPreference = "SMS",
                            TargetAnimalsJson = "[\"tiger\",\"lion\",\"elephant\",\"bear\",\"wolf\"]"
                        },
                        new
                        {
                            UserId = 3,
                            DetectionThreshold = 0.85f,
                            HighlightSavePath = "Media/HighlightFrames/Observer",
                            NotificationPreference = "Email",
                            TargetAnimalsJson = "[\"bird\",\"deer\",\"fox\",\"rabbit\"]"
                        });
                });

            modelBuilder.Entity("ZooTrack.Models.Alert", b =>
                {
                    b.HasOne("ZooTrack.Models.Detection", "Detection")
                        .WithMany("Alerts")
                        .HasForeignKey("DetectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooTrack.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooTrack.Models.Animal", b =>
                {
                    b.HasOne("ZooTrack.Models.Detection", "Detection")
                        .WithMany("Animals")
                        .HasForeignKey("DetectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detection");
                });

            modelBuilder.Entity("ZooTrack.Models.Detection", b =>
                {
                    b.HasOne("ZooTrack.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooTrack.Models.Event", "Event")
                        .WithMany("Detections")
                        .HasForeignKey("EventId");

                    b.HasOne("ZooTrack.Models.Media", "Media")
                        .WithMany("Detections")
                        .HasForeignKey("MediaId");

                    b.Navigation("Device");

                    b.Navigation("Event");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ZooTrack.Models.DetectionValidation", b =>
                {
                    b.HasOne("ZooTrack.Models.Detection", "Detection")
                        .WithMany()
                        .HasForeignKey("DetectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detection");
                });

            modelBuilder.Entity("ZooTrack.Models.Log", b =>
                {
                    b.HasOne("ZooTrack.Models.Detection", "Detection")
                        .WithMany()
                        .HasForeignKey("DetectionId");

                    b.HasOne("ZooTrack.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("Detection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooTrack.Models.Media", b =>
                {
                    b.HasOne("ZooTrack.Models.Device", "Device")
                        .WithMany("Media")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ZooTrack.Models.UserSettings", b =>
                {
                    b.HasOne("ZooTrack.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("ZooTrack.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooTrack.Models.Detection", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Animals");
                });

            modelBuilder.Entity("ZooTrack.Models.Device", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("ZooTrack.Models.Event", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("ZooTrack.Models.Media", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("ZooTrack.Models.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Logs");

                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
